### ISSUE TITLE
Syntax error :Can’t get script "com.lifepillar/ASUnit". How can I resolve this 

### ISSUE THREAD

**Issue by syammala** [lifepillar/ASUnit#2]
I followed the Documentation given and installed ASUnit and ASmake. When I tried to run the Test Template.applescript. I am seeing above syntax error.

**Comment by lifepillar** [comment]
That likely means that ASUnit is not installed in the right location. Please verify that  the file `ASUnit.scptd` exists in `/Users/YOUR_USERNAME/Library/Script Libraries/com.lifepillar`.

**Comment by syammala** [comment]
Yeah , I changed location, it is working fine. Thank you
