### ISSUE TITLE
Can we test an apple script that is using scripting additions

### ISSUE THREAD

**Issue by syammala** [lifepillar/ASUnit#3]
I want to test an apple script which in run time loads another apple script and calls some functions. When I try to run these tests I see an error message as cant get <<data 00000000000000000000000000000000000000000000000243428000000000000000

**Comment by lifepillar** [comment]
That should definitely be possible, but with so few details I can't help much. Can you provide an example?

**Comment by syammala** [comment]
Yes I was able acess, But only when I load another apple script locally rather than globally.  Can we get code coverage using ASunit framework.

**Comment by syammala** [comment]
Yeah its possible. I have seen that error when I loaded a file which is saved from script debugger, the file extension might be differed internally.
